In [1]:
from google.colab import files
uploaded = files.upload()

Saving train_data.csv to train_data.csv

In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv('train_data.csv')

In [4]:
df_train = df_train[['Text data','Label']]

In [5]:
df_train.head(5)

                                           Text data     Label
0  Waiting for my mind to have a breakdown once t...  moderate
1  My new years resolution : I'm gonna get my ass...  moderate
2  New year : Somone else Feeling like 2020 will ...  moderate
3  My story I guess : Hi, Im from Germany and my ...  moderate
4  Sat in the dark and cried myself going into th...  moderate

In [6]:
df_train.Label.unique()

array(['moderate', 'not depression', 'severe'], dtype=object)

In [7]:
type(df_train)

pandas.core.frame.DataFrame

In [8]:
print(df_train['Label'].value_counts())

moderate          3678
not depression    2755
severe             768
Name: Label, dtype: int64

In [9]:
df_train.isnull().sum()

Text data    0
Label        0
dtype: int64

In [10]:
df_train.describe()

                                                Text data     Label
count                                                7201      7201
unique                                               7006         3
top     im tired : i feel really shitty for being clin...  moderate
freq                                                    2      3678

In [11]:
!pip install simpletransformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting simpletransformers
  Downloading simpletransformers-0.63.11-py3-none-any.whl (250 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.7/250.7 kB 8.9 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.22.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2.27.1)
Requirement already satisfied: tqdm>=4.47.0 in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (4.65.0)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2022.10.31)
Collecting transformers>=4.6.0 (from simpletransformers)
  Downloading transformers-4.29.2-py3-none-any.whl (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 96.8 MB/s eta 0:00:00
Collecting datasets (from simpletransformers)
  Downloading datasets-2.12.0-py3-none-any.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 52.7 MB/s eta 0:00:00
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.10.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.2.2)
Collecting seqeval (from simpletransformers)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorboard in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2.12.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.5.3)
Collecting tokenizers (from simpletransformers)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 102.4 MB/s eta 0:00:00
Collecting wandb>=0.10.32 (from simpletransformers)
  Downloading wandb-0.15.3-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 98.5 MB/s eta 0:00:00
Collecting streamlit (from simpletransformers)
  Downloading streamlit-1.22.0-py2.py3-none-any.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 121.5 MB/s eta 0:00:00
Collecting sentencepiece (from simpletransformers)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 96.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers>=4.6.0->simpletransformers) (3.12.0)
Collecting huggingface-hub<1.0,>=0.14.1 (from transformers>=4.6.0->simpletransformers)
  Downloading huggingface_hub-0.14.1-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 29.5 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.6.0->simpletransformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.6.0->simpletransformers) (6.0)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (8.1.3)
Collecting GitPython!=3.1.29,>=1.0.0 (from wandb>=0.10.32->simpletransformers)
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 26.2 MB/s eta 0:00:00
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (5.9.5)
Collecting sentry-sdk>=1.0.0 (from wandb>=0.10.32->simpletransformers)
  Downloading sentry_sdk-1.24.0-py2.py3-none-any.whl (206 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.5/206.5 kB 29.1 MB/s eta 0:00:00
Collecting docker-pycreds>=0.4.0 (from wandb>=0.10.32->simpletransformers)
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Collecting pathtools (from wandb>=0.10.32->simpletransformers)
  Downloading pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting setproctitle (from wandb>=0.10.32->simpletransformers)
  Downloading setproctitle-1.3.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (67.7.2)
Requirement already satisfied: appdirs>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (1.4.4)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (3.20.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (3.4)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (9.0.0)
Collecting dill<0.3.7,>=0.3.0 (from datasets->simpletransformers)
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 16.8 MB/s eta 0:00:00
Collecting xxhash (from datasets->simpletransformers)
  Downloading xxhash-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 29.6 MB/s eta 0:00:00
Collecting multiprocess (from datasets->simpletransformers)
  Downloading multiprocess-0.70.14-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 19.4 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (2023.4.0)
Collecting aiohttp (from datasets->simpletransformers)
  Downloading aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 45.0 MB/s eta 0:00:00
Collecting responses<0.19 (from datasets->simpletransformers)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->simpletransformers) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->simpletransformers) (2022.7.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->simpletransformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->simpletransformers) (3.1.0)
Requirement already satisfied: altair<5,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (4.2.2)
Collecting blinker>=1.0.0 (from streamlit->simpletransformers)
  Downloading blinker-1.6.2-py3-none-any.whl (13 kB)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (5.3.0)
Collecting importlib-metadata>=1.4 (from streamlit->simpletransformers)
  Downloading importlib_metadata-6.6.0-py3-none-any.whl (22 kB)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (8.4.0)
Collecting pympler>=0.9 (from streamlit->simpletransformers)
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 kB 22.6 MB/s eta 0:00:00
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (13.3.4)
Requirement already satisfied: tenacity<9,>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (8.2.2)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (4.5.0)
Requirement already satisfied: tzlocal>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (4.3)
Collecting validators>=0.2 (from streamlit->simpletransformers)
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting pydeck>=0.1.dev5 (from streamlit->simpletransformers)
  Downloading pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 111.3 MB/s eta 0:00:00
Requirement already satisfied: tornado>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (6.3.1)
Collecting watchdog (from streamlit->simpletransformers)
  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 12.4 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.54.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (3.4.3)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (2.3.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (0.40.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<5,>=3.2.0->streamlit->simpletransformers) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<5,>=3.2.0->streamlit->simpletransformers) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<5,>=3.2.0->streamlit->simpletransformers) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<5,>=3.2.0->streamlit->simpletransformers) (0.12.0)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb>=0.10.32->simpletransformers) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (23.1.0)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets->simpletransformers)
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 17.2 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->datasets->simpletransformers)
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->datasets->simpletransformers)
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 34.7 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp->datasets->simpletransformers)
  Downloading frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 23.0 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp->datasets->simpletransformers)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting gitdb<5,>=4.0.1 (from GitPython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers)
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.5 MB/s eta 0:00:00
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard->simpletransformers) (1.3.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=1.4->streamlit->simpletransformers) (3.15.0)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->streamlit->simpletransformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->streamlit->simpletransformers) (2.14.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.10/dist-packages (from tzlocal>=1.1->streamlit->simpletransformers) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from validators>=0.2->streamlit->simpletransformers) (4.4.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard->simpletransformers) (2.1.2)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers)
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit->simpletransformers) (0.19.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit->simpletransformers) (0.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard->simpletransformers) (3.2.2)
Requirement already satisfied: tzdata in /usr/local/lib/python3.10/dist-packages (from pytz-deprecation-shim->tzlocal>=1.1->streamlit->simpletransformers) (2023.3)
Building wheels for collected packages: seqeval, validators, pathtools
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16165 sha256=62378aeacf802845823ced0aec72a37400e9098ab583460a5a43112bdc2e4696
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=4e829c7c5dbb4b7d616484eb92fec8785c247ab101d64bc13b93063926c59ea0
  Stored in directory: /root/.cache/pip/wheels/f2/ed/dd/d3a556ad245ef9dc570c6bcd2f22886d17b0b408dd3bbb9ac3
  Building wheel for pathtools (setup.py) ... done
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8791 sha256=f37546dda7d927bb1febf50013e9736fdb4f49da36f0e38d546d4773d61947ab
  Stored in directory: /root/.cache/pip/wheels/e7/f3/22/152153d6eb222ee7a56ff8617d80ee5207207a8c00a7aab794
Successfully built seqeval validators pathtools
Installing collected packages: tokenizers, sentencepiece, pathtools, xxhash, watchdog, validators, smmap, setproctitle, sentry-sdk, pympler, multidict, importlib-metadata, frozenlist, docker-pycreds, dill, blinker, async-timeout, yarl, responses, pydeck, multiprocess, huggingface-hub, gitdb, aiosignal, transformers, seqeval, GitPython, aiohttp, wandb, streamlit, datasets, simpletransformers
Successfully installed GitPython-3.1.31 aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 blinker-1.6.2 datasets-2.12.0 dill-0.3.6 docker-pycreds-0.4.0 frozenlist-1.3.3 gitdb-4.0.10 huggingface-hub-0.14.1 importlib-metadata-6.6.0 multidict-6.0.4 multiprocess-0.70.14 pathtools-0.1.2 pydeck-0.8.1b0 pympler-1.0.1 responses-0.18.0 sentencepiece-0.1.99 sentry-sdk-1.24.0 seqeval-1.2.2 setproctitle-1.3.2 simpletransformers-0.63.11 smmap-5.0.0 streamlit-1.22.0 tokenizers-0.13.3 transformers-4.29.2 validators-0.20.0 wandb-0.15.3 watchdog-3.0.0 xxhash-3.2.0 yarl-1.9.2

In [12]:
!pip install clean-text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting clean-text
  Downloading clean_text-0.6.0-py3-none-any.whl (11 kB)
Collecting emoji<2.0.0,>=1.0.0 (from clean-text)
  Downloading emoji-1.7.0.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting ftfy<7.0,>=6.0 (from clean-text)
  Downloading ftfy-6.1.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 7.6 MB/s eta 0:00:00
Requirement already satisfied: wcwidth>=0.2.5 in /usr/local/lib/python3.10/dist-packages (from ftfy<7.0,>=6.0->clean-text) (0.2.6)
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171033 sha256=159d62082bac9a222ce4f2aba3daee8fd85473baa41ae671b9b2fd3e9fb1ccd4
  Stored in directory: /root/.cache/pip/wheels/31/8a/8c/315c9e5d7773f74b33d5ed33f075b49c6eaeb7cedbb86e2cf8
Successfully built emoji
Installing collected packages: emoji, ftfy, clean-text
Successfully installed clean-text-0.6.0 emoji-1.7.0 ftfy-6.1.1

In [13]:
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
import re

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [14]:
def preprocess(sentence):
  sentence=str(sentence)
  sentence=sentence.lower()
  cleanr=re.compile('<.*?>')
  cleantext=re.sub(cleanr,'',sentence)
  rem_url=re.sub(r'http\S+','',cleantext)
  rem_num=re.sub('[0-9]+','',rem_url)
  rem_tag=re.sub(r'@\S+','',rem_num)
  tokenizer=RegexpTokenizer(r'\w+')
  tokens=tokenizer.tokenize(rem_tag)
  filtered_words=[w for w in tokens if len(w)>0 if not w in stopwords.words('english')]
  return " ".join(tokens)

df_train['Text data']=df_train['Text data'].map(lambda s:preprocess(s))
df_train.head(20)

                                            Text data     Label
0   waiting for my mind to have a breakdown once t...  moderate
1   my new years resolution i m gonna get my ass i...  moderate
2   new year somone else feeling like will be ther...  moderate
3   my story i guess hi im from germany and my eng...  moderate
4   sat in the dark and cried myself going into th...  moderate
5   i will probably end it when my mum isn t aroun...  moderate
6   fuck left abusive relationship moved in with a...  moderate
7   i am at a new year s eve party and i want to c...  moderate
8   death of my father my father died in the begin...  moderate
9   empty and stuck in a loop every day in any ord...  moderate
10  it s officially here no one has wished me a ha...  moderate
11  marriage dog police so i m turning this year i...  moderate
12  i don t want to die i just want to stop living...  moderate
13  happy new year fuck will be bettexaxaxaxaxaxa ...  moderate
14  i almost cried while my family was wishing eac...  moderate
15  my dad got me bottle of irish cream yesterday ...  moderate
16  everybody has left me i don t know why i am ma...  moderate
17  don t know what to do it s new year s eve i wa...  moderate
18  lonely new year so i don t know if this belong...  moderate
19  i hate my life i wish i had never been born it...  moderate

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_train.Label = le.fit_transform(df_train.Label)
df_train.head(20)

                                            Text data  Label
0   waiting for my mind to have a breakdown once t...      0
1   my new years resolution i m gonna get my ass i...      0
2   new year somone else feeling like will be ther...      0
3   my story i guess hi im from germany and my eng...      0
4   sat in the dark and cried myself going into th...      0
5   i will probably end it when my mum isn t aroun...      0
6   fuck left abusive relationship moved in with a...      0
7   i am at a new year s eve party and i want to c...      0
8   death of my father my father died in the begin...      0
9   empty and stuck in a loop every day in any ord...      0
10  it s officially here no one has wished me a ha...      0
11  marriage dog police so i m turning this year i...      0
12  i don t want to die i just want to stop living...      0
13  happy new year fuck will be bettexaxaxaxaxaxa ...      0
14  i almost cried while my family was wishing eac...      0
15  my dad got me bottle of irish cream yesterday ...      0
16  everybody has left me i don t know why i am ma...      0
17  don t know what to do it s new year s eve i wa...      0
18  lonely new year so i don t know if this belong...      0
19  i hate my life i wish i had never been born it...      0

In [16]:
from simpletransformers.classification import ClassificationModel

In [17]:
model = ClassificationModel(
    'roberta', 'roberta-base', num_labels=3, use_cuda=True,
    args={
        "reprocess_input_data": True,
        "use_cached_eval_features": False,
        "overwrite_output_dir": True,
        "num_train_epochs": 1
    }
)

Downloading (…)lve/main/config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.dense.weight', 'roberta.pooler.dense.weight', 'lm_head.bias', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.out_proj.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [18]:
model.train_model(df_train)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:612: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(

  0%|          | 0/7201 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/901 [00:00<?, ?it/s]

(901, 0.8405675517599802)

DEVELOPMENT DATA

In [19]:
from google.colab import files
uploaded = files.upload()

Saving dev_data.csv to dev_data.csv

In [20]:
df_eval = pd.read_csv('dev_data.csv')
df_eval = df_eval[['textdata','Classlabels']]
df_eval

                                               textdata Classlabels
0     Im scared : This is it. I lie to myself every ...    moderate
1     New to this but just wanted to vent : I just f...    moderate
2     I’m sad : It’s kinda always been an issue. I w...    moderate
3     Lonely but not alone. : All of my immediately ...    moderate
4     This year has been trash. : I dont know why I’...    moderate
...                                                 ...         ...
3240  Feeling lonely. : Hi reddit, I haven’t posted ...      severe
3241  When would suicide be right? : So I got back f...      severe
3242  Lowest I’ve ever been ever. : To make a long s...      severe
3243  Does the Toxoplasma Gondii ruined my life ? (f...      severe
3244  Getting the correct diagnosis : Currently goin...      severe

[3245 rows x 2 columns]

In [21]:
df_eval['textdata']=df_eval['textdata'].map(lambda s:preprocess(s))
df_eval.head(20)

                                             textdata Classlabels
0   im scared this is it i lie to myself every day...    moderate
1   new to this but just wanted to vent i just fin...    moderate
2   i m sad it s kinda always been an issue i woul...    moderate
3   lonely but not alone all of my immediately fam...    moderate
4   this year has been trash i dont know why i m p...    moderate
5   needed to yell into the void i m a pos i m cur...    moderate
6   i don t know why i m here anymore i feel like ...    moderate
7   i dont want to be here anymore i dont wanna di...    moderate
8   antidepressants do antidepressants help if you...    moderate
9   tms my doctor wants me to do tms for my depres...    moderate
10  my fault it s my fault it s my fault not knowi...    moderate
11  how should i explain to my mom about my mental...    moderate
12  dealing with morbid depression after the loss ...    moderate
13  i m starting to imagine and plan life without ...    moderate
14  feeling detached from myself people disassocia...    moderate
15  depressed international student studying in ca...    moderate
16  i do nothing to keep myself calm i tried to ke...    moderate
17  weight gain due to depression let me rephrase ...    moderate
18  i think i m depressed i m f and i m empty and ...    moderate
19  hope is a drug i do not care what anyone says ...    moderate

In [22]:
df_eval['textdata']

0       im scared this is it i lie to myself every day...
1       new to this but just wanted to vent i just fin...
2       i m sad it s kinda always been an issue i woul...
3       lonely but not alone all of my immediately fam...
4       this year has been trash i dont know why i m p...
                              ...
3240    feeling lonely hi reddit i haven t posted to t...
3241    when would suicide be right so i got back from...
3242    lowest i ve ever been ever to make a long stor...
3243    does the toxoplasma gondii ruined my life firs...
3244    getting the correct diagnosis currently going ...
Name: textdata, Length: 3245, dtype: object

In [23]:
le = LabelEncoder()
df_eval.Classlabels = le.fit_transform(df_eval.Classlabels)
df_eval.head(20)

                                             textdata  Classlabels
0   im scared this is it i lie to myself every day...            0
1   new to this but just wanted to vent i just fin...            0
2   i m sad it s kinda always been an issue i woul...            0
3   lonely but not alone all of my immediately fam...            0
4   this year has been trash i dont know why i m p...            0
5   needed to yell into the void i m a pos i m cur...            0
6   i don t know why i m here anymore i feel like ...            0
7   i dont want to be here anymore i dont wanna di...            0
8   antidepressants do antidepressants help if you...            0
9   tms my doctor wants me to do tms for my depres...            0
10  my fault it s my fault it s my fault not knowi...            0
11  how should i explain to my mom about my mental...            0
12  dealing with morbid depression after the loss ...            0
13  i m starting to imagine and plan life without ...            0
14  feeling detached from myself people disassocia...            0
15  depressed international student studying in ca...            0
16  i do nothing to keep myself calm i tried to ke...            0
17  weight gain due to depression let me rephrase ...            0
18  i think i m depressed i m f and i m empty and ...            0
19  hope is a drug i do not care what anyone says ...            0

In [24]:

df_eval.tail(20)

                                               textdata  Classlabels
3225  first day taking venlafaxine so my doctor has ...            2
3226  medication is not helping my doctor diagnosed ...            2
3227  scars and sex im a year old dude that still se...            2
3228  mass shooting in germany hey my name is thomas...            2
3229  still waiting on my psychiatrist appointment r...            2
3230  i m losing it i ve been struggling with ptsd a...            2
3231  too broken to change what matters i m depresse...            2
3232  today i opened up to my friends and it was a m...            2
3233  fluoxetine to pristiq question hey i m switchi...            2
3234  d a f depressed as fuck i ve been diagnosed wi...            2
3235  made it to i didnt think i would see cuz of th...            2
3236  it sucks when you try to get help and it blows...            2
3237  if antidepressants make me gain even more weig...            2
3238  i m tried of coming here and writing this agai...            2
3239  i never want to do the things that i know will...            2
3240  feeling lonely hi reddit i haven t posted to t...            2
3241  when would suicide be right so i got back from...            2
3242  lowest i ve ever been ever to make a long stor...            2
3243  does the toxoplasma gondii ruined my life firs...            2
3244  getting the correct diagnosis currently going ...            2

In [25]:
result, model_outputs, wrong_predictions = model.eval_model(df_eval)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:1454: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(

  0%|          | 0/3245 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/406 [00:00<?, ?it/s]

In [26]:
print(model_outputs)

[[ 1.48144531  0.03436279 -1.76367188]
 [ 1.19824219  0.57470703 -2.11328125]
 [ 1.1953125   0.28076172 -1.79492188]
 ...
 [ 0.68359375  1.125      -2.27539062]
 [ 0.17932129  0.71337891 -1.40039062]
 [-0.45947266 -0.84277344  1.22851562]]

In [27]:
print(result)

{'mcc': 0.2864790411323386, 'eval_loss': 0.7675750769417862}

In [28]:
print(model.predict(["Thank you, that really helps. Now I feel ten times worse."]))

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

(array([1]), array([[ 0.42797852,  1.99902344, -2.84375   ]]))

In [29]:
print(len(wrong_predictions))

1225

In [30]:
print(wrong_predictions[6])

{'guid': 24, 'text_a': 'i wish i could go back in time back to when i smiled back to when i was motivated and excited about life back to when i had friends and family back to when i could make a sound decision and not fuck my life up everyday becomes harder than the last', 'text_b': None, 'label': 0}

In [31]:
predictions, raw_outputs = model.predict(df_eval['textdata'].tolist())
print(predictions)
print(raw_outputs)

  0%|          | 0/3245 [00:00<?, ?it/s]

  0%|          | 0/406 [00:00<?, ?it/s]

[0 0 0 ... 1 1 2]
[[ 1.48144531  0.03436279 -1.76367188]
 [ 1.19824219  0.57470703 -2.11328125]
 [ 1.1953125   0.28076172 -1.79492188]
 ...
 [ 0.68359375  1.125      -2.27539062]
 [ 0.17932129  0.71337891 -1.40039062]
 [-0.45947266 -0.84277344  1.22851562]]

In [32]:
print(predictions)

[0 0 0 ... 1 1 2]

In [33]:
print(len(predictions))

3245

In [34]:
from sklearn.metrics import classification_report
print(classification_report(df_eval.Classlabels,predictions))

              precision    recall  f1-score   support

           0       0.77      0.66      0.71      2169
           1       0.46      0.53      0.49       848
           2       0.34      0.57      0.43       228

    accuracy                           0.62      3245
   macro avg       0.52      0.59      0.54      3245
weighted avg       0.66      0.62      0.63      3245

In [35]:
print(wrong_predictions)

[{'guid': 5, 'text_a': 'needed to yell into the void i m a pos i m currently also physically sick and at home with my parents my parents really want me to work during my break from uni i want to but at the same time i really don t i m too scared to even make phone calls my social anxiety has gotten no much worse since i stopped therapy i can do some more things but for other things my anxiety is worse i hate applying for jobs and the rejection everytime makes me feel so fucking shitty if i could at least work from home it would make things easier i don t have any skills to qualify for anything i m still a uni student i ve been struggling with depression i have thoughts about killing myself daily and i don t know how to ask for help i have no friends because i distanced myself from everyone all of this is all my fault i m stuck in a major i hate and i can t find a job i m so useless i m the biggest disappointment i can t stand looking at myself in a mirror i try to stay distracted but nothing is fun i m just wasting my life away doing nothing all day i don t deserve a life i hate uni i hate my life if i just killed myself it would all be over i m scared about what will happen if i don t succeed i don t want my parents to get angry at me or blame themselves i wanna have a good life but i don t think i m even able to at this point i can t stop being like this i hate myself so much i just want everything to stop', 'text_b': None, 'label': 0}, {'guid': 8, 'text_a': 'antidepressants do antidepressants help if your not depressed i started taking them to get through a rough patch and they have helped me does this mean i technically have depression because i read online that antidepressants don t help if your not depressed', 'text_b': None, 'label': 0}, {'guid': 9, 'text_a': 'tms my doctor wants me to do tms for my depression has anyone done tms or is doing it i was just want to know it is worth it', 'text_b': None, 'label': 0}, {'guid': 13, 'text_a': 'i m starting to imagine and plan life without me at years of age and countless meds doctors therapists i am very tired really really tired it s taking all i have now to make it through the day and perform at work but i m thinking how will my family make it if i can t contribute my part financially we are so broke and my husband already works very long hours my body hurts so badly and my mind is so tired i have no friends left and all i have is my immediate family which consists of kids and my husband i ve been so strong for them for so long and hid this for as long as i could i can t anymore i just can t everyday i am holding a bottle of pills in my hand i could take all of my meds at once plus the bottle of sleeping pills and call it a day i want to so bad to just check out i have to go to work today to a job i hate and pretend again i eventually hate all of my jobs my flaw i m really good at everything i do which is amazing because i m such a fake tired of being fake it s a lot of work i tell jokes i make people laugh or at least i used to now i m just by myself i am trying to get into see someone but amazingly no one around here is taking new patients or they don t take my insurance and i just want to say well i will just go kill myself thanks so all i have is here with everybody else who wants to end it', 'text_b': None, 'label': 0}, {'guid': 19, 'text_a': 'hope is a drug i do not care what anyone says hope is the most addicting substance there is it s a drug that pumps up your mind and gives you a smile you think is real until it s taken away and it hurts so much your body goes through withdrawals', 'text_b': None, 'label': 0}, {'guid': 21, 'text_a': 'happy people piss me off i don t know why but when i see people that are so care free and happy i just get mad like they re taunting me or something saying hey i m happier than you loneliness isn t a problem for me and i will rub it in your face i know most people that are generally happy don t think that but to me it feels like it', 'text_b': None, 'label': 0}, {'guid': 24, 'text_a': 'i wish i could go back in time back to when i smiled back to when i was motivated and excited about life back to when i had friends and family back to when i could make a sound decision and not fuck my life up everyday becomes harder than the last', 'text_b': None, 'label': 0}, {'guid': 27, 'text_a': 'i got a little mental breakdown at school today in math class was the day where my mask fell and i got a breakdown we were allowed to listen to music and maybe i played some sad songs i layed on my arm and solved a question when suddenly one song came i thought about what am i doing here and why i am so worthless i started crying silently and still solved the equasions my stuff was wet but i think no one noticed that i can t do it any longer its breaking me and its starts to ruin my life', 'text_b': None, 'label': 0}, {'guid': 29, 'text_a': 'just need to vent i think i m having a depressive episode and it s really scary the last time i went through this was around years ago and it almost took my life i m so terrified of it getting to that point again and all i keep thinking about is how this something i m going to have to deal with for the rest of my life i m going to have always live in fear of the darkness creeping back in this time though i am trying to be proactive and get some therapy unfortunately the soonest i could see someone is the end of next month so until then i am just trying to get by i m trying so hard to keep my head above water because my life is different this time i don t live at my moms house anymore and i m miles away from the support system i had last time i have bills to pay and work at as a manager at a clothing store i have to keep my shit together because i only have myself to depend on this time but i can feel myself slowly start to stink and it s so scary i feel so alone all the time and it sucks i feel like a burden to anyone i try to reach out to and the fact that i am so far away from my family and most of my friends is so isolating i m trying to make new friends where i live now but it s so hard when all i want to do after work is lay in bed and cry idk what the point of this post is but i just need to let this all out i tend to keep things bottled up so i m trying to do better because i know it s better for me i don t really care if nobody responds i just really needed to just shout this into the void', 'text_b': None, 'label': 0}, {'guid': 33, 'text_a': 'i don t know what to do the past year has been very difficult i don t have the energy to get out of bed and go to my classes so i ve been dropped from most of them the medicine i m taking worked in the beginning but now i m not seeing any results at all if anything i m worse off now than i was before because my brain is saying well if it s not the medicine then it s obviously your fault that you re screwing your life up i m just so tired', 'text_b': None, 'label': 0}, {'guid': 34, 'text_a': 'even eating has become a chore everything is exhausting and meaningless i just want to lie down in darkness close my eyes and never open them again', 'text_b': None, 'label': 0}, {'guid': 36, 'text_a': 'job interview today i have a job interview in a few hours i m currently on the couch almost curled up in a ball i want to just skip the whole thing i haven t prepared i haven t even left the house in weeks i don t want to go but i need to work my depression and anxiety are worse than ever despite being on medication i used to be high functioning but i think the meds actually make it easier for me to blow things off and procrastinate i m in hell right now', 'text_b': None, 'label': 0}, {'guid': 39, 'text_a': 'are there any subreddits where i can ask for donations turns out therapy is expensive and i might need a bit of help with the initial session which is more costly the subsequent sessions i might be able to manage myself anyone know a subreddit that can help', 'text_b': None, 'label': 0}, {'guid': 42, 'text_a': 'why does my depression physically hurt my boody isi', 'text_b': None, 'label': 0}, {'guid': 45, 'text_a': 'i m completely numb the things i used to like i don t care about video games are boring and annoying music doesn t sound good anymore i have no interest in friendships or relationships anymore', 'text_b': None, 'label': 0}, {'guid': 50, 'text_a': 'no one except a few people actually understand depression my teachers are always on my back about wearing my favorite hoodie because it is the only thing that makes me feel comfortable in my own skin my parents are yelling at me cause my marks are going down not realizing that maybe i need a break and rest to get myself back on track my brother just continually annoys and harasses me saying i don t have depression and so is everyone in my school there are only people in my life that actually understand and don t give me shit for what i m going through so i m just done with this', 'text_b': None, 'label': 0}, {'guid': 51, 'text_a': 'i can t get out of bed please help me how do you guys do it', 'text_b': None, 'label': 0}, {'guid': 55, 'text_a': 'just broke up with girlfriend few nights ago and i ve been taking it really hard it s hard again to find motivation for anything this is a right person wrong place type of situation if that s even a thing i really care love and adore this girl but her mental problems were too big of a handful for me especially since i already have a hard enough time dealing with my own mental problems she tried committing suicide a few weeks back and that moment was incredibly stressful and haunting for me i felt like since that if we were to stay together it would happen to her again at some point and i couldn t handle that and if we broke up it would happen again right then and there i felt trapped this has been a lot on my mind and i feel bad for not being able to stand by her anymore while she fights her demons i m still fighting my own and i feel like i can t win my fight if i stay with her i have worked too hard for far too long to make the progress i ve made as far as my mental health goes i used to be in and out of the behavioral hospital since an early age and lately i have been going to the gym getting plenty of sunlight meditating literally doing anything i can that i believe will make me feel better since we ve broken up i thought i d be immediately able to jump back into this and return to the goal orientated overachiever i know i can be but instead i just feel grief loneliness regret and shame it s hard for me to get out of bed and get these things done work is the only thing that s keeping me going right now but as soon as that ends i m just back in bed with no motivation i haven t been able to eat and i m already underweight so i feel like it s taking its toll on me all i want to do is sleep and shut out existence when you feel like you ve hit rock bottom again what s something you do to get your motivation back', 'text_b': None, 'label': 0}, {'guid': 74, 'text_a': 'my last therapists and my psychiatrist advised me to find a girlfriend this is actually great advice but there s one small problem i m the least desirable person on this entire planet i have no real friends and my family hates me because they know i don t care about anything or anyone whenever i walk around in public people give me the dirty look assuming that i m on drugs i have people screaming at me swearing at me or insulting me at every workplace i set foot into because i don t like social interaction and i look like the guy who doesn t want to be at work which is a fair judgement dating isn t just about looks people like people who care about life and who s going to care about them and i don t care about anything or anyone so yeah i m a loser just needed to vent', 'text_b': None, 'label': 0}, {'guid': 75, 'text_a': 'it s not worth it i think about life a lot it s hard not to think about it while aimlessly scrolling through facebook and reacting to posts that i didn t actually like because i just wanted to please whoever shared them walking down the street surrounded by people uncomfortably staring at me sitting in class surrounded by so called friends of mine who openly and honestly love each other but can never really bring themselves to accept me looking at my crush who doesn t even know i exist and is instead looking adoringly at someone else letting out a frustrated sigh whenever anyone talks on the group chat and people start spamming it with a hundred messages a minute and so on and so forth so many painful reminders that i m supposed to be living supposed to be existing just like everyone else that instead i m just unnatural i try to force myself to feel anything to care about what people my age usually care about a social life a partner a well paying job a party where i could fuck some stranger and forget about them in the morning a popular song an instagram account with a thousand followers but i can t care about anything or anyone anymore nothing brings me happiness sadness or any of those normal feelings all i feel is emptiness and anger for reasons i don t even know myself i can t connect with people and i always lose focus whenever someone s talking to me i feel so alone in a noisy lecture room and nobody stops to look at me once unless they don t have anyone else to whine and gush to suddenly i become the most important person in the world just because i m conveniently there at the right place at the right time to be used as a punching bag i watch sappy romantic movies from time to time and listen to love songs from various decades often sometimes i wonder to myself will someone ever feel this way about me will someone ever hold me in their arms and tell me there s nowhere else they d rather be but here with me my parents are the only two people in the world who ever loved me what happens when they die who else will love me and genuinely give a shit about me ask whether i ate today or drank any water or changed out of my clothes myself i fucking hate myself there s no one else i d rather see dead but me so who else nobody that s who i might as well accept this fact right now so i don t get too shocked and upset when i find myself an old withering human being dying alone in my cold bed i m alone in this world i don t feel anything i ve become so apathetic that i just wanna drop out of college pack my bags and disappear forever if i don t kill myself first i don t know why i still wake up in the morning i don t know why i bother it s not worth living for this pathetic life of mine it s not worth it', 'text_b': None, 'label': 0}, {'guid': 77, 'text_a': 'sometimes people can be either too oblivious or choose not to care and they may not intend to harm us but it does hurt removed', 'text_b': None, 'label': 0}, {'guid': 78, 'text_a': 'last night i told myself i would get up on time get to school and spend the day working on class projects today i stayed in bed for hours didn t leave my house and watched youtube videos all day how quickly will i be fired if i ever get a job', 'text_b': None, 'label': 0}, {'guid': 81, 'text_a': 'will i be happy someday removed', 'text_b': None, 'label': 0}, {'guid': 83, 'text_a': 'just call me tillicum i have a great job i ve been here years the pay is really good my bosses and co workers are kind and appreciative our clientele for the most part are amazing and i spend the majority of my morning commute wishing i d get into a hideous car accident so that i don t have to go in today the thing is while it s a great job a d i m lucky to have it it is also pointless repetitive meaningless work with no upward mobility i m front staff and the one with seniority everyday when i leave i m no further ahead life than when i walked in in the morning years ago sure it helped me get a car pay me rent help my family get my dog the hours are long i m working most weekends makes it really hard to socialize i feel like that orca who went crazy in his tank and started murdering his trainers you swim circles long enough anyone will go crazy i don t know if it s just the depression talking or maybe i ll get over it maybe it s stupid to quit why would it be any different at another job it d also be kind of a dirtbag move one co worker is out with cancer right now it s been stressful for everyone i ve been training the new temporary girl for th last month and that s even more stress do i have the right to add to that stress i don t know what to do any more', 'text_b': None, 'label': 0}, {'guid': 84, 'text_a': 'do you ever feel like you don t have depression and are just a selfish a hole removed', 'text_b': None, 'label': 0}, {'guid': 85, 'text_a': 'i hate myself what do i do i was doing really well in school but it all slipped and now i feel completely trapped school is impossible to go to and i just absolutely fucking hate myself what do i do i have no idea how to get out of this', 'text_b': None, 'label': 0}, {'guid': 90, 'text_a': 'what is the easiest way to commit a mass murder removed', 'text_b': None, 'label': 0}, {'guid': 95, 'text_a': 'even if i make money what would i even do with it if i dont care about myself or life in general this is such a nonsense spoiled thing to think', 'text_b': None, 'label': 0}, {'guid': 96, 'text_a': 'music as a coping mechanism do you ever just listen to songs that artists have clearly written about someone specific and imagine that they re singing it to you or that someone would sing it to you since it s so beautiful like you just wish that someone thought about you that way or loved you like that whenever i start feeling worse i notice i do this to myself and while it makes me feel kind of good in the end it depresses me even more because i ll never be that special and precious to someone that they ll write a beautiful song with me in mind anyway if anyone does this please share songs that make you feel like this bonus points if it makes you want to levitate into a sunset', 'text_b': None, 'label': 0}, {'guid': 97, 'text_a': 'i lied to my therapist so that she wouldn t talk about a topic that causes most of my depression because i was too embarrassed removed', 'text_b': None, 'label': 0}, {'guid': 98, 'text_a': 'anyone else has horrible mood swings removed', 'text_b': None, 'label': 0}, {'guid': 99, 'text_a': 'is there a way of fighting depression alone removed', 'text_b': None, 'label': 0}, {'guid': 101, 'text_a': 'everything s to good to be true every time i feel like i m close to something i just end up getting torn away from it with anything with people with my passions with everything i live the most bland life in the world and i just want something to give me a kick of motivation towards anything', 'text_b': None, 'label': 0}, {'guid': 102, 'text_a': 'my moms getting rid of my dog we got a puppy a month ago i love him to the end of the world and back but sometimes i have a hard enough time just trying to brush my teeth in the morning that i let her take care of him instead i do my absolute best i really really try to take care of him and i feel like it s helping me a lot but lately my mom is getting annoyed with me and is threatening to get rid of the dog just an hour ago i was hiding in my room with him and playing with him after she started getting mad at me about not trying hard enough and she barged in grabbed him and walked out i just don t know what to do anymore should i just let her get rid of the dog', 'text_b': None, 'label': 0}, {'guid': 104, 'text_a': 'not everyone is supposed to live i ve been thinking about this lately some of us are weak some of us are weaker its natural selection dude if im fed up with my life i might just kms thats all', 'text_b': None, 'label': 0}, {'guid': 105, 'text_a': 'went to talk to an academic advisor at my local community college today male tired of being unhappy and making a month decided to further my education someone told me to look into med lab tech i looked into it money looked like enough to be

In [36]:
not_depressed = 0
moderate = 0
depressed = 0

for x in wrong_predictions:
    if x.label == 0:
        not_depressed += 1
    elif x.label == 1:
        moderate += 1
    elif x.label == 2:
        depressed += 1

print("Not Depressed:", not_depressed)
print("Moderate:", moderate)
print("Depressed:", depressed)

Not Depressed: 729
Moderate: 399
Depressed: 97

In [37]:
from google.colab import files
uploaded = files.upload()

Saving test_data.csv to test_data.csv

In [38]:
import pandas as pd

# Read the CSV file and select the desired column
df = pd.read_csv('test_data.csv')
selected_column = df['Textdata']

# Make predictions on the selected column
predictions = model.predict(selected_column.tolist())

# Print the predictions
print(predictions)

  0%|          | 0/499 [00:00<?, ?it/s]

  0%|          | 0/63 [00:00<?, ?it/s]

(array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 1, 2,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 2, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0]), array([[ 0.94189453,  0.59375   , -1.93652344],
       [ 1.21289062,  0.34985352, -1.87695312],
       [ 0.46044922,  1.63476562, -2.44921875],
       ...,
       [ 0.77685547,  1.5703125 , -2.73046875],
       [ 0.78173828,  0.76660156, -1.93847656],
       [ 0.93261719,  0.15844727, -1.52929688]]))

In [40]:
prediction_array = predictions[0]
print(prediction_array)

[0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1
 2 1 0 0 1 1 1 0 1 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 1
 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 2 0 1 1 1 1 0 0 0
 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0 2 1 1 0 0 1 1 1 0 1 1
 1 1 2 1 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 1 1 1 1 0 1 0 1 1 0 1
 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 2 1 1 2 1 1
 0 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 2 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1
 1 0 1 1 0 0 2 2 1 0 1 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 1 1 0 1 2 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0
 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 1 1 0 1 0
 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 2 0 0 1 0 1 1 0 0
 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 2 0 1 1 1 1 0 0 0 0 2 2 0 0 0 1
 0 0 0 1 0 1 2 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 2 1 0 0 1 0 1 1 1 2 1
 1 0 1 0 1 1 1 0 2 1 1 1 0 0 1 1 0 0]

In [41]:
import csv


# Open the existing CSV file
with open('test_data.csv', 'r') as file:
    reader = csv.reader(file)
    rows = list(reader)

# Add a new column header for the prediction values
header = rows[0]
header.append('Prediction')

# Add values to the new column
for i in range(1, len(rows)):
    if i - 1 < len(prediction_array):
        rows[i].append(prediction_array[i - 1])
    else:
        rows[i].append(None)

# Write the updated data to a new CSV file
with open('updated_test5.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(rows)

In [42]:
import pandas as pd

# Read the updated CSV file
df_updated = pd.read_csv('updated_test5.csv')

# Print the head 20 rows
print(df_updated.head(20))

           Pid                                           Textdata  Prediction
0    test_id_1  This is me. Don?? get me wrong, it?? better th...           0
1    test_id_2  I hate that people don?? understand that i don...           0
2    test_id_3  But here I am, 24 years old man and doing exac...           1
3    test_id_4  I?? trapped inside. Does anyone else get that ...           1
4    test_id_5  I read a lot of posts on here of people strugg...           1
5    test_id_6  Thank you, that really helps. Now I feel ten t...           1
6    test_id_7  I don?? know if that makes sense. What I mean ...           0
7    test_id_8  Does anyone else feel this way? This has been ...           1
8    test_id_9    The first 6 words of the title is accurate too.           1
9   test_id_10                                            Fuck ??           1
10  test_id_11  Just curious if anyone else affected by this p...           1
11  test_id_12  She was only 67. She told me every so often ab...           1
12  test_id_13  Basically what the title says and my current s...           1
13  test_id_14  i feel this way around everyone, friends, fami...           1
14  test_id_15  I can?? even remember the last time i woke up ...           1
15  test_id_16  Happens to me a lot. Cooking, walking to class...           1
16  test_id_17  Like ???\n\n\nI posted on AskReddit asking non...           0
17  test_id_18  I can?? imagine how many days I have wasted to...           0
18  test_id_19  It feels like the harder I try to better mysel...           1
19  test_id_20  It's just so fucking tiresome. You see it ever...           1

In [43]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.29.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.27.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)

In [44]:
!pip install huggingface_hub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.10/dist-packages (0.14.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (3.12.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2023.4.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (2.27.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.65.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub) (23.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub) (3.4)